title:              HUFS_smP
email:              semin3211@hufs.ac.kr
description:        A Blog Theme by Start Bootstrap
author:             Semin Paik
url:                "https://HUFSsmP.github.io"

# Social Profiles
twitter_username:   SMP
github_username:    HUFSsmP
facebook_username:  SMP
instagram_username:  semin_03_19
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
